ALTER TABLE chat_rooms
    ADD COLUMN IF NOT EXISTS nickname VARCHAR(120),
    ADD COLUMN IF NOT EXISTS bubble_theme VARCHAR(20) NOT NULL DEFAULT 'ROSE',
    ADD COLUMN IF NOT EXISTS background_theme VARCHAR(20) NOT NULL DEFAULT 'PLAIN';
